Style/Encoding:
  Enabled: fasle

Metrics/LineLength:
  Max: 150

Bundler/DuplicatedGem:
  Description: 'Checks for duplicate gem entries in Gemfile'
  Enabled: true
  VersionAdded: '0.46'
  Include:
    - '**/*.gemfile'
    - '**/Gemfile'
    - '**/gems.rb'
